sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t akshat2604/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true akshat2604/react-test npm test

after_success:
  - docker build -t akshat2604/multi-client-10-14 ./client
  - docker build -t akshat2604/multi-nginx-10-14 ./nginx
  - docker build -t akshat2604/multi-server-10-14 ./server
  - docker build -t akshat2604/multi-worker-10-14 ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push akshat2604/multi-client-10-14
  - docker push akshat2604/multi-nginx-10-14
  - docker push akshat2604/multi-server-10-14
  - docker push akshat2604/multi-worker-10-14

